dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: trfore/docker-ubuntu2404-systemd:latest
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: /etc/ansible/ansible.cfg

verifier:
  name: ansible
