---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  tags:
    - webserver
    - installation

- name: Start and enable Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
  when: ansible_virtualization_type != "docker"
  tags:
    - webserver
    - service

- name: Configure Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx
  tags:
    - webserver
    - configuration

- name: Ensure nginx log is world-readable
  ansible.builtin.file:
    path: /var/log/nginx/access.log
    mode: '0644'
  when: ansible_facts['distribution'] == 'Ubuntu'
  tags:
    - webserver
    - configuration

- name: Validate Nginx config
  ansible.builtin.command: nginx -t
  changed_when: false
  tags:
    - webserver
    - validation
